version: '3.8'

services:
  web:
    build:
      context: .
      args:
        CACHEBUST: "latest"  # You can change this value to force a rebuild (or use $(date +%s) in your shell)
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: unless-stopped